name: Build Minesweeper
on:
  push:
    paths:
    - 'Projects/Minesweeper/**'
  pull_request:
    paths:
    - 'Projects/Minesweeper/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
    - run: dotnet build "Projects\Minesweeper\Minesweeper.csproj" --configuration Release