name: Minesweeper CI

on:
  push:
    branches: [ main ]
    paths:
      - 'Games/Minesweeper/**'
      - 'Tests/Minesweeper.Tests/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'Games/Minesweeper/**'
      - 'Tests/Minesweeper.Tests/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build "Games\Minesweeper\Minesweeper.csproj" --no-restore
      
    - name: Test
      run: dotnet test "Tests\Minesweeper\Minesweeper.Tests.csproj" --no-build --verbosity normal
